# Use the official Node.js 18 image as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock files
COPY package.json yarn.lock ./

# Install dependencies using Yarn
RUN yarn install

# Copy the rest of the application code
COPY . .

# Build the Next.js application
RUN yarn build

# Set the environment variable for production
ENV NODE_ENV=production

# Expose the port the app runs on
EXPOSE 9000

# Start the Next.js application
CMD ["yarn", "start:dev"]
